services:
  stack-info:
    image: ${REGISTRY_NAMESPACE:-el-sca-ansamble}/el-sca-resilient-updater:${IMAGE_TAG:-1.0.0}
    build: null

  grype-updater:
    image: ${REGISTRY_NAMESPACE:-el-sca-ansamble}/el-sca-resilient-updater:${IMAGE_TAG:-1.0.0}
    build: null

  artifact-extractor:
    image: ${REGISTRY_NAMESPACE:-el-sca-ansamble}/el-sca-extractor:${IMAGE_TAG:-1.0.0}
    build: null

  cve-bin-tool-updater:
    image: ${REGISTRY_NAMESPACE:-el-sca-ansamble}/el-sca-cve-bin-tool:${IMAGE_TAG:-1.0.0}
    build: null

  cve-bin-tool-scanner:
    image: ${REGISTRY_NAMESPACE:-el-sca-ansamble}/el-sca-cve-bin-tool:${IMAGE_TAG:-1.0.0}
    build: null

  db-admin:
    image: ${REGISTRY_NAMESPACE:-el-sca-ansamble}/el-sca-resilient-updater:${IMAGE_TAG:-1.0.0}
    build: null

  mock-feed-server:
    image: ${REGISTRY_NAMESPACE:-el-sca-ansamble}/el-sca-resilient-updater:${IMAGE_TAG:-1.0.0}
    build: null

  report-collector:
    image: ${REGISTRY_NAMESPACE:-el-sca-ansamble}/el-sca-resilient-updater:${IMAGE_TAG:-1.0.0}
    build: null
